apiVersion: apps/v1
kind: Deployment
metadata:
  name: #
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: #
       maxUnavailable: #
  replicas: #
  selector:
    matchLabels:
      app: #
  template:
    metadata:
      labels:
        app: #
    spec:
      containers:
      - name: #
        image: #
        ports:
        - containerPort: #